### ISSUE TITLE
Make clear that this is an old version

### ISSUE THREAD

**Issue by gonsolo** [ValveSoftware/vkd3d#2]
There should be a big fat warning that this is a very old version!

**Comment by kisak-valve** [comment]
Hello @gonsolo, it looks like the initial integration of VKD3D-Proton needed some changes from upstream VKD3D-Proton to make it work, but since then it became easier to use the upstream Github/HansKristian-Work/vkd3d-proton repository.

Hypothetically, there might be some urgent issue that needed an immediate fix, and in that case this repo would get a new branch with the deviation from upstream VKD3D-Proton.

Setting that aside, it's unusual for any open source project to have documentation added stating that it is outdated unless it has been replaced by a different implementation, which leaves this fork in an awkward limbo. It continues to exist because removing it would break building Proton 4.11 and 5.0 from the source code.

**Comment by Buggem** [comment]
It isn't really an old version, check the d3d-master branch. Last commit 28 days ago.
